title: Ziyang Wang # your name (or website title) here
logo: "/images/avatar.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master degree candidate seeking a full-time software engineer position. Expected to start as soon as possible.
  <br><br>
  A self-starter taking lead in various projects and striving to drive their success. One of two only CS new undergrads graduated with distinction. A team player communicating in fluent Mandarin and English. Opportunity given; satisfaction paid back.
  <br><br>
  <a href="https://www.linkedin.com/in/ziyangwangishere/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
